config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  resources :users
  get "experiences/new", to: "experiences#new"
  post "experiences", to: "experiences#create"
  resources :experiences do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index]
  resources :bookings, only: [:destroy]

  resources :experiences do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :experience
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :experience
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :reviews
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
    @experience = Experience.find(params[:experience_id])
    @user = @experience.user

  end

  def create
    @booking = Booking.create(
      experience: Experience.find(params[:experience_id]),
      user: current_user
    )
    redirect_to bookings_path
  end


  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to experience_path(@booking.experience)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        activity @@ :query \
        OR place @@ :query \
      "
      @experiences = Experience.where(sql_query, query: "%#{params[:query]}%")
    else
      @experiences = Experience.all
    end
  end

  def show
    @experience = Experience.find(params[:id])
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.save
    redirect_to experience_path(@experience)
  end

  def new
    @experience = Experience.new
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    Experience.find(params[:id]).update(experience_params)
    redirect_to "/experiences/#{params[:id]}"
  end

  def destroy
    Experience.find(params[:id]).destroy
    redirect_to '/experiences'
  end

  private

  def experience_params
    params.require(:experience).permit(:activity, :place, :start_date, :end_date, :photo, :price, :description,:user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @experiences = Experience.all
    @experience = Experience.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @experience = Experience.find(params[:experience_id])
    @user = @experience.user
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    set_experience
    @review.user = current_user
    @review.save
    if @review.save
      redirect_to experience_path(@review.experience)
    else
      render :new
    end
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to experience_path(@review.experience)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :user_id, :experience_id)
  end

  def set_experience
    @review.experience = Experience.find(params[:experience_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, expect: []

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    User.find(params[:id]).update(user_params)
    redirect_to "/users/#{params[:id]}"
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<%= simple_form_for @booking, :url => booking_path(@booking), :method => :delete do |f|%>
  <%= f.submit "Destroy", class: "btn btn-primary" %>
<% end %>

app/views/bookings/index.html.erb
<div class="wrapper">
  <div class="container mt-5 mb-4">
    <div class="experience-index__banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1008&q=80);">
    <div class="row">
      <div class="col-6 offset-3 experience-index__banner__content">
        <div class="experience-index__title">My next Pickalife <span class="secondary-color">adventures</span>.
        </div>
        <%= render 'shared/searchbar', experience: @experience %>
      </div>
    </div>
    </div>
  </div>
  <div class="container mb-4">
    <%= render 'shared/titleSubtitle', title: 'My bookings', subtitle: "It's time to pack ", subtitle_important: 'soon' %>
    <div class="row mb-4">
      <% @bookings.each do |booking| %>
      <div class="col-xs-6 col-sm-3 my-2">
        <%= render 'shared/card', experience: booking.experience %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>YOUR BOOKING IS DONE</h1>

app/views/experiences/_info_window.html.erb
<h2><%= experience.name %></h2>
<p><%= experience.address %></p>

app/views/experiences/edit.html.erb
<%= render 'shared/form', experience: @experience %>
<%= simple_form_for @experience, :url => experience_path(@experience), :method => :delete do |f|%>
  <%= f.submit "Destroy", class: "btn btn-primary" %>
<% end %>

app/views/experiences/index.html.erb
<div class="wrapper">
  <div class="container mt-5 mb-4">
    <div class="experience-index__banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1008&q=80);">
    <div class="row">
      <div class="col-6 offset-3 experience-index__banner__content">
        <div class="experience-index__title">Where would you like to <span class="secondary-color">go</span>?
        </div>
        <%= render 'shared/searchbar', experience: @experience %>
      </div>
    </div>
    </div>
  </div>
  <div class="container mb-4">
    <%= render 'shared/titleSubtitle', title: 'Live your dreams', subtitle: 'Travel to the other part of the world in just a few ', subtitle_important: 'clicks' %>
    <div class="row mb-4">
      <% @experiences.each do |experience| %>
      <div class="col-xs-6 col-sm-3 my-2">
        <%= render 'shared/card', experience: experience %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/experiences/new.html.erb
<%= render 'shared/homeForm', experience: @experience %>

app/views/experiences/show.html.erb
<div class="wrapper">
  <div class="container mt-5">
    <div class="row">
      <div class="col-12">
        <div class="banner -search -show" style="background-image: url('<%= cl_image_path @experience.photo.key %>')");">
          <div class="banner__title"><%= @experience.activity %> in <span class="secondary-color"><%= @experience.place %></span>.
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-5">
      <div class="col-12">
        <div class="experience">
          <%= link_to root_path, class: 'experience__back' do %>
          <%= icon('fas', 'arrow-left') %> Back to
          experiences
          <% end %>
          <div>
            <%= link_to edit_experience_path(@experience), class: 'experience__setting' do %>
            <%= icon('fas', 'edit') %>
            <% end %>
            <%= link_to experience_path(@experience), method: :delete, data: { confirm: "Are you sure?" }, class: 'experience__setting' do %>
            <%= icon('fas', 'trash-alt') %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-5">
        <%= render 'shared/titleSubtitle', title: 'The host', subtitle: 'Discover who is your next favorite ', subtitle_important: 'Pickalifer' %>
        <%= render 'shared/userCard', experience: @experience %>
      </div>
      <div class="col-5 offset-2">
        <%= render 'shared/titleSubtitle', title: '', subtitle: 'What they say about ', subtitle_important: @experience.user.name %>
        <div class="row">
          <div class="col-12">
            <% @experience.reviews.each do |review| %>
            <div class="experience__host experience__host__review mb-3">
              <div class="experience__host_details">
                <div class="experience__host__photo experience__host__photo__review">
                  <div class="experience__host__avatar" style="background-image: url('<%= cl_image_path review.user.photo.key %>')">
                  </div>
                  <div class="">
                    <h3 class="experience__host__name"><%= review.user.name %></h3>
                    <h4 class="experience__host__place"><%= review.user.experiences.first.place %>, <%= review.user.gender %>, <%= review.user.age %> years old.</h4>
                  </div>
                </div>
                <h3 class="experience__description">"<%= review.comment %>"</h3>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>PickaLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%#= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://d19m59y37dris4.cloudfront.net/directory/1-4/img/photo/photo-1501621965065-c6e1cf6b53e2.jpg);">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 offset-sm-1">
        <%= render 'shared/form', experience: @experience %>
      </div>
    </div>
  </div>
</div>
<div class="wrapper">
  <div class="container mb-5">
    <%= render 'shared/titleSubtitle', title: 'Latests experiences', subtitle: 'The best life experiences you can find, ', subtitle_important: 'worldwide' %>
    <div class="row my-4">
      <% @experiences.last(4).each do |experience| %>
      <div class="col-xs-6 col-sm-3 my-2">
        <%= render 'shared/card', experience: experience %>
      </div>
      <% end %>
    </div>
    <%= link_to "Discover all experiences >>", experiences_path, class: "home__cta" %>
  </div>
  <div class="container mb-5">
    <%= render 'shared/titleSubtitle', title: 'Live your dreams', subtitle: 'Travel to the other part of the world in just a few ', subtitle_important: 'clicks' %>
    <div class="row">
      <div class="col-12">
        <%= render 'shared/bannerSearch' %>
      </div>
    </div>
  </div>
  <div class="container mb-5">
    <%= render 'shared/titleSubtitle', title: 'Top-rated experiences', subtitle: 'The best you can live ', subtitle_important: 'out there' %>
    <div class="row mb-4">
      <% @experiences.sample(4).each do |experience|%>
      <div class="col-xs-4 col-sm-3 my-2">
        <%= render 'shared/card', experience: experience %>
      </div>
      <% end %>
    </div>
    <%= link_to experiences_path, class: "home__cta" do %>
    <div>See the best experiences out there >></div>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<div>
  <% @reviews.each do |review| %>
    <div> Rating:<%= review.rating %></div>
    <div> <%= review.comment %></div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for([@experience, Review.new]) do |f| %>

  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.button :submit, 'leave a review', class: 'btn -primary -full'%>
<% end %>

app/views/reviews/show.html.erb
<div>
    <div> Rating:<%= @review.rating %></div>
    <div> <%= @review.comment %></div>
    <div>
            <%= link_to experience_review_path(@review), class: 'experience__setting' do %>
            <%= icon('fas', 'edit') %>
            <% end %>
            <%= link_to experience_review_path(@review), method: :delete, data: { confirm: "Are you sure?" }, class: 'experience__setting' do %>
            <%= icon('fas', 'trash-alt') %>
            <% end %>
   </div>
</div>

app/views/shared/_bannerSearch.html.erb
<div class="banner -search mb-5" style="background-image: url(https://images.unsplash.com/photo-1474452926969-af7bfdb9ca39?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80);">
  <div class="text-center">
    <h2 class="-search__title">Pimp your life</h2>
    <%= link_to "Search your dreams", experiences_path, class: "btn -primary" %>
  </div>
</div>

app/views/shared/_bookingForm.html.erb
<%= simple_form_for([experience, Booking.new]) do |f| %>
   <%= link_to "LIVE THE EXPERIENCE", new_experience_booking_path(experience),  data: { confirm: "Do you confirm?"}, class: "btn -primary -full" %>
<% end %>

app/views/shared/_card.html.erb
<div class="card">
  <%= link_to experience_path(experience) do %>
  <div class="card__img" style="background-image: url('<%= cl_image_path experience.photo.key %>')">
    <div class="card__title">
      <%= experience.activity %>
    </div>
  </div>
  <% end %>
  <div class="card__info">
    <div class="card__place">
      <%= experience.place %>
      <div class="card__date">
        <%= experience.start_date.strftime("on %a. %d of %B") %>
      </div>
    </div>
    <div class="card__price">
      <%= experience.price %>,00€
    </div>
    <div class="card__description">
      <%= experience.description.truncate(90) %>
    </div>
    <div class="card__rating">
      <span class="card__icon"><%= icon('fas', 'star', class: 'strong') %></span>
      <%= rand(3.0..5).to_s.truncate(4, omission: '') %><span class="soft-text"> (293)</span>
    </div>
  </div>
  <div class="card__bottom">
    <%= link_to "Live it", experience_path(experience), class: "card__cta" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer__links">
    <a href="#"><i class="fab fa-instagram footer__icon"></i></a>
    <a href="#"><i class="fab fa-facebook footer__icon"></i></a>
    <a href="#"><i class="fab fa-twitter footer__icon"></i></a>
  </div>
  <div class="footer__text">
    This footer was made with <span class="footer__icon"><%= icon('fas', 'heart', class: 'strong') %></span> by PickaLife.
  </div>
</div>

app/views/shared/_form.html.erb
<div class="form ">
  <%= simple_form_for experience, html: { class: "form__card"} do |f| %>
  <h2 class="form__title">Share your life experiences and make people's dreams come <span class="secondary-color">true.</span></h2>
  <div class="wrapper">
    <div class="row">
      <div class="col-6">
        <div class="form__column">
          <%= f.input :activity, placeholder: 'Hiking' %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
        </div>
      </div>
      <div class="col-6">
        <div class="form__column">
          <%= f.input :description, placeholder: 'Climb the Machu Picchu', :input_html => {:rows => 1} %>
          <%= f.input :price, placeholder: '10,00' %>
          <%= f.input :place, placeholder: 'Machu Picchu, Peru' %>
          <% if current_user%>
              <%= f.association :user, :as => :hidden, :input_html => { :value => current_user.id }  %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= f.input :photo, label: 'Upload your image here'%>
      </div>
    </div>
    <%= f.submit :class => 'btn -primary -full' %>
  </div>
  <% end %>
</div>

app/views/shared/_homeForm.html.erb
<div class="homeForm ">
  <%= simple_form_for experience, html: { class: "homeForm__form"} do |f| %>
  <h2 class="homeForm__title">Share your life experiences and make people's dreams come <span class="secondary-color">true.</span></h2>
  <div class="wrapper">
    <div class="row">
      <div class="col-6">
        <div class="homeForm__column">
          <%= f.input :activity %>
          <%= f.input :place %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
        </div>
      </div>
      <div class="col-6">
        <div class="homeForm__column">
          <%= f.input :description, :input_html => {:rows => 1} %>
          <%= f.input :price%>
          <%= f.input :photo%>
          <%= f.input :photo_cache, as: :hidden %>
          <% if current_user %>
            <%= f.association :user, :as => :hidden, :input_html => { :value => current_user.id }  %>
          <% end %>

        </div>
      </div>
    </div>
    <%= f.submit :class => 'button-primary homeForm__btn' %>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar">
    <%= link_to "PickaLife", root_path, class: "navbar__logo" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Share your life", new_experience_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Live your dream", experiences_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link secondary-color" %>
        </li>
        <!-- <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li> -->
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%= form_tag experiences_path, method: :get do %>
<%= text_field_tag :query,
params[:query],
class: "form-control searchbar",
placeholder: "Alabama baby!"
%>
<%= submit_tag "Search", class: "searchbar__input" %>
<% end %>

app/views/shared/_titleSubtitle.html.erb
<div class="wrapper mb-4">
  <h2 class="home__title"><%= title %></h2>
  <h4 class="home__subtitle"><%= subtitle %> <span class="secondary-color"><%= subtitle_important %>.</span></h4>
</div>

app/views/shared/_userCard.html.erb
<div class="experience__host">
  <div class="experience__host_details">
    <div class="experience__host__photo">
      <div class="experience__host__avatar" style="background-image: url('<%= cl_image_path experience.user.photo.key %>')">
      </div>
      <div class="">
        <h3 class="experience__host__name"><%= experience.user.name %></h3>
        <h4 class="experience__host__place"><%= experience.place %>, <%= experience.user.gender %>, <%= experience.user.age %> years old.</h4>
      </div>
    </div>
    <h3 class="experience__description">"<%= experience.description %>"</h3>
    <%= link_to 'LIVE THE EXPERIENCE', experience_bookings_path(experience), method: :post, data: { confirm: "Are you sure you want to book this experience?"}, class: "btn -primary -full"%>
  </div>
</div>

app/views/users/edit.html.erb
<div><%= @user.email %></div>
<%= simple_form_for @user do |f|%>
  <%= f.input :email %>
  <%= f.submit "Edit", class: "btn btn-primary" %>
<% end %>

<%= simple_form_for @user, :url => user_path(@user), :method => :delete do |f|%>
  <%= f.submit "Destroy", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<div><%= @user.name %></div>